# Copyright (c) 2025 OntoLogics (Seth & Axion). All rights reserved.
# Licensed under the VTR Public License (VTR-PL), Version 1.0 (the "License").
# A copy of the License is available in the root/vtr_standard/poc/LICENSE file.
# This code is distributed WITHOUT ANY WARRANTY.

from typing import Optional
from pydantic import BaseModel, Field


class HardwareSignature(BaseModel):
    """
    Represents the cryptographic hardware signature generated by the PRNU sensor.
    """

    public_key: str = Field(
        ..., description="The public verification key derived from the sensor ID."
    )
    zk_proof: str = Field(..., description="The simulated Zero-Knowledge Proof.")
    liveness_flag: bool = Field(
        ..., description="Result of the passive liveness check."
    )
    timestamp: float = Field(..., description="Unix timestamp of the capture.")
    merkle_root: str = Field(
        ..., description="The Merkle Tree Root of the video content."
    )
    location_block_hash: str = Field(
        ..., description="Hash of the location data block."
    )
    previous_signature_link: Optional[str] = Field(
        None, description="The zk_proof of the previous VTR sidecar in the chain."
    )
    nonce: str = Field(
        ..., description="A unique value to prevent economic replay attacks."
    )


class LegalAssertions(BaseModel):
    """
    Represents legal claims and permissions associated with the content.
    """

    x_vtr_ai_training: bool = Field(
        False, description="Whether the content may be used for AI training."
    )
    copyright_notice: str = Field(..., description="Copyright and DMCA notice.")


class VTRSidecar(BaseModel):
    """
    The top-level schema for the VTR V2.0 Sidecar file.
    """

    vtr_version: str = Field(
        "2.2", pattern=r"^2\.[0-2]$", description="The version of the VTR standard."
    )
    hardware_signature: HardwareSignature
    legal_assertions: LegalAssertions
    # economic_data field has been removed in V2.2. See docs/archive/economics_v1.md for historical context.
